// flow-typed signature: ee0844b1239e8308c2e74309c77ffa85
// flow-typed version: <<STUB>>/alertify.js_v1.0.12/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alertify.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alertify.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alertify.js/dist/js/alertify' {
  declare module.exports: any;
}

declare module 'alertify.js/dist/js/ngAlertify' {
  declare module.exports: any;
}

declare module 'alertify.js/karma-ci.conf' {
  declare module.exports: any;
}

declare module 'alertify.js/karma.conf' {
  declare module.exports: any;
}

declare module 'alertify.js/src/js/alertify' {
  declare module.exports: any;
}

declare module 'alertify.js/src/js/ngAlertify' {
  declare module.exports: any;
}

declare module 'alertify.js/src/ts/alertify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alertify.js/dist/js/alertify.js' {
  declare module.exports: $Exports<'alertify.js/dist/js/alertify'>;
}
declare module 'alertify.js/dist/js/ngAlertify.js' {
  declare module.exports: $Exports<'alertify.js/dist/js/ngAlertify'>;
}
declare module 'alertify.js/karma-ci.conf.js' {
  declare module.exports: $Exports<'alertify.js/karma-ci.conf'>;
}
declare module 'alertify.js/karma.conf.js' {
  declare module.exports: $Exports<'alertify.js/karma.conf'>;
}
declare module 'alertify.js/src/js/alertify.js' {
  declare module.exports: $Exports<'alertify.js/src/js/alertify'>;
}
declare module 'alertify.js/src/js/ngAlertify.js' {
  declare module.exports: $Exports<'alertify.js/src/js/ngAlertify'>;
}
declare module 'alertify.js/src/ts/alertify.js' {
  declare module.exports: $Exports<'alertify.js/src/ts/alertify'>;
}
