// flow-typed signature: e0616191bf8244d9d553a0194355b7d7
// flow-typed version: <<STUB>>/contentful-management_vvx.x.x/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contentful-management'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contentful-management' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contentful-management/dist/contentful-management.browser' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/contentful-management.browser.min' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/contentful-management.legacy' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/contentful-management.legacy.min' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/contentful-management.node' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/contentful-management.node.min' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/contentful-management' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/create-contentful-api' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/create-space-api' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/enhance-with-methods' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/api-key' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/asset' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/content-type' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/editor-interface' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/entry' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/index' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/locale' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/organization' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/personal-access-token' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/role' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/snapshot' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/space-membership' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/space' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/ui-extension' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/upload' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/user' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/entities/webhook' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/error-handler' {
  declare module.exports: any;
}

declare module 'contentful-management/dist/es-modules/instance-actions' {
  declare module.exports: any;
}

declare module 'contentful-management/tonic-example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contentful-management/dist/contentful-management.browser.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.browser'>;
}
declare module 'contentful-management/dist/contentful-management.browser.min.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.browser.min'>;
}
declare module 'contentful-management/dist/contentful-management.legacy.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.legacy'>;
}
declare module 'contentful-management/dist/contentful-management.legacy.min.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.legacy.min'>;
}
declare module 'contentful-management/dist/contentful-management.node.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.node'>;
}
declare module 'contentful-management/dist/contentful-management.node.min.js' {
  declare module.exports: $Exports<'contentful-management/dist/contentful-management.node.min'>;
}
declare module 'contentful-management/dist/es-modules/contentful-management.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/contentful-management'>;
}
declare module 'contentful-management/dist/es-modules/create-contentful-api.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/create-contentful-api'>;
}
declare module 'contentful-management/dist/es-modules/create-space-api.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/create-space-api'>;
}
declare module 'contentful-management/dist/es-modules/enhance-with-methods.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/enhance-with-methods'>;
}
declare module 'contentful-management/dist/es-modules/entities/api-key.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/api-key'>;
}
declare module 'contentful-management/dist/es-modules/entities/asset.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/asset'>;
}
declare module 'contentful-management/dist/es-modules/entities/content-type.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/content-type'>;
}
declare module 'contentful-management/dist/es-modules/entities/editor-interface.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/editor-interface'>;
}
declare module 'contentful-management/dist/es-modules/entities/entry.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/entry'>;
}
declare module 'contentful-management/dist/es-modules/entities/index.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/index'>;
}
declare module 'contentful-management/dist/es-modules/entities/locale.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/locale'>;
}
declare module 'contentful-management/dist/es-modules/entities/organization.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/organization'>;
}
declare module 'contentful-management/dist/es-modules/entities/personal-access-token.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/personal-access-token'>;
}
declare module 'contentful-management/dist/es-modules/entities/role.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/role'>;
}
declare module 'contentful-management/dist/es-modules/entities/snapshot.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/snapshot'>;
}
declare module 'contentful-management/dist/es-modules/entities/space-membership.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/space-membership'>;
}
declare module 'contentful-management/dist/es-modules/entities/space.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/space'>;
}
declare module 'contentful-management/dist/es-modules/entities/ui-extension.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/ui-extension'>;
}
declare module 'contentful-management/dist/es-modules/entities/upload.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/upload'>;
}
declare module 'contentful-management/dist/es-modules/entities/user.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/user'>;
}
declare module 'contentful-management/dist/es-modules/entities/webhook.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/entities/webhook'>;
}
declare module 'contentful-management/dist/es-modules/error-handler.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/error-handler'>;
}
declare module 'contentful-management/dist/es-modules/instance-actions.js' {
  declare module.exports: $Exports<'contentful-management/dist/es-modules/instance-actions'>;
}
declare module 'contentful-management/tonic-example.js' {
  declare module.exports: $Exports<'contentful-management/tonic-example'>;
}
